apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: minio-data-pvc
spec:
  volumeName: minio-data-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
