apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: tempo-configmap
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: minio-service:9000
          access_key: ENTER_MINIO_ACCESS_KEY
          secret_key: ENTER_MINIO_SECRET_KEY
          insecure: true
